import { X } from 'lucide-react'

export default function TermsModal({ isOpen, onClose }) {
  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white dark:bg-[#141B2D] rounded-2xl shadow-2xl border border-gray-100 dark:border-white/10 w-full max-w-2xl max-h-[85vh] overflow-y-auto">
        <div className="sticky top-0 bg-white dark:bg-[#141B2D] border-b border-gray-100 dark:border-white/5 px-6 py-4 flex items-center justify-between z-10">
          <h2 className="font-heading font-bold text-lg text-gray-900 dark:text-white">Terms of Service</h2>
          <button onClick={onClose} className="w-8 h-8 rounded-full flex items-center justify-center hover:bg-gray-100 dark:hover:bg-white/10 transition-colors">
            <X className="w-4 h-4 text-gray-500 dark:text-gray-400" />
          </button>
        </div>

        <div className="px-6 py-5 text-sm text-gray-600 dark:text-gray-300 leading-relaxed space-y-5">
          <p className="text-xs text-gray-400 dark:text-gray-500">Last updated: April 5, 2026</p>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">1. Acceptance of Terms</h3>
            <p>By accessing or using LaunchPlan AI, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service.</p>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">2. Description of Service</h3>
            <p>LaunchPlan AI is an AI-powered marketing plan generator that creates personalized 30-day marketing strategies based on your product details. The service includes plan generation, plan storage, PDF export, and inline editing capabilities.</p>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">3. User Accounts</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must create an account to generate and save marketing plans.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You must provide accurate information when creating your account.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">4. Free and Paid Plans</h3>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong>Free tier:</strong> Up to 5 marketing plans with save and revisit history. PDF exports include a watermark.</li>
              <li><strong>Pro tier:</strong> Unlimited plans, clean PDF exports, and priority generation.</li>
              <li><strong>Agency tier:</strong> Includes client workspaces, white-label PDFs, and team collaboration features.</li>
            </ul>
            <p className="mt-2">We reserve the right to modify pricing and plan features with reasonable notice.</p>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">5. AI-Generated Content</h3>
            <p>Marketing plans generated by LaunchPlan AI are created using artificial intelligence and are provided as suggestions only. You retain full ownership of the content generated for your products. We do not guarantee the accuracy, effectiveness, or suitability of any generated marketing strategy. You are responsible for reviewing and adapting the content before use.</p>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">6. Acceptable Use</h3>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Use the service for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer or exploit the AI system.</li>
              <li>Share your account credentials with others.</li>
              <li>Generate content that promotes illegal activities or violates others' rights.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">7. Limitation of Liability</h3>
            <p>LaunchPlan AI is provided "as is" without warranties of any kind. We are not liable for any business decisions made based on AI-generated marketing plans. Our total liability shall not exceed the amount you paid for the service in the preceding 12 months.</p>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">8. Termination</h3>
            <p>We reserve the right to suspend or terminate your account if you violate these terms. You may delete your account at any time, which will remove your stored plans and personal data.</p>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">9. Changes to Terms</h3>
            <p>We may update these terms from time to time. Continued use of the service after changes constitutes acceptance of the revised terms.</p>
          </section>

          <section>
            <h3 className="font-heading font-semibold text-gray-900 dark:text-white mb-2">10. Contact</h3>
            <p>For questions about these terms, please reach out to us on Twitter or via our support channels.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
